services:
  argus:
    build: .           
    env_file: .env
    volumes:
      - ./config:/config:ro
      - ./state:/state
    environment:
      - TZ=America/Toronto
    ports:
      - "8080:8080"